name: Test Release Pipelines

on:
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/pull_release.yml
      - .github/workflows/_build_test_upload.yml

permissions:
  id-token: write
  contents: read
  
jobs:
  build_test_upload:
    if: github.repository == 'pytorch/data'
    uses: ./.github/workflows/_build_test_upload.yml
    with:
      branch: "main"
      pre_dev_release: true
      pytorch_version: ""
      do-upload: true
    secrets:
      CONDA_TEST_PYTORCHBOT_TOKEN: ""
